name: pixels2flutter
description: Convert and screenshot to a working Flutter app screen.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: 3.2.0
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
